### PR TITLE
Reconnect semantics, acks&nacks, 'cleaner' disconnects

### PR DESCRIPTION
**Pull request by storkme**
hi,

I've made this pull request mostly to address #33 and #19, but also to add in support for ACKS/NACKS, and alter the semantics of the 'disconnect' handling to better fit my use case (in my mind the remote server disconnecting us is an error, and should attempt to reconnect).

Two tests are failing in this PR, but honestly I can't see the value in these two tests anyway:
* 'check the ERROR callback fires when we receive and error frame when disconnecting'
* 'check the ERROR callback is removed from the client on disconnect'
I would be inclined to remove these two tests as to me they seem a little contrived, but perhaps there's something I'm missing here?

### CODE REVIEW

**Comment by easternbloc** [comment]
Hi @storkme can you rebase out the merge commit to master please?

**Comment by easternbloc** [comment]
This one: eff6061

**Comment by easternbloc** [comment]
The rest of it looks great by the way.

**Comment by storkme** [comment]
hi @easternbloc, sorry but I didn't quite follow - you want me to remove the merge commit?

I'm not all that experienced with git, could you give me some pointers?

Thanks.

**Comment by easternbloc** [comment]
you should be able to rebase it out of your branch. Something like

```git rebase -i HEAD~6``` then when it brings up the interactive rebaser just delete that last merge commit. It's just so the commit history is clean.

**Comment by easternbloc** [comment]
then you'll need to force push the branch as you've rewrote history so you'll need to ```--force``` the branch when you push it!

**Comment by easternbloc** [comment]
hope that helps.

**Comment by storkme** [comment]
I think I've managed it by doing a hard reset to the appropriate point, does it look better now?

**Comment by easternbloc** [comment]
Cool thanks. I'm just gonna check through those two failing tests when I have some time and check what value they add.

**Comment by gknapp** [comment]
Any idea when this PR will be merged? Have you had a chance to review the failing tests?

**Comment by easternbloc** [comment]
Had a look. Pretty sure @storkme is correct. Those tests can be removed. @storkme any chance you can remove them in this PR?

**Comment by easternbloc** [comment]
thanks @storkme this is now merged and published in 0.6 on npm. Cheers

**Comment by storkme** [comment]
Apologies for not removing those tests, have been too busy recently :-1:

many thanks for the merge @easternbloc :+1:

**Pull request merged**
